create table caesars.comp_detail (
	id bigserial not null
		constraint comp_detail_pkey
			primary key,
	i_dmid numeric,
	c_prop_cd varchar(255),
	i_comp_number numeric,
	d_comp_issue_date date,
	d_comp_issue_time interval,
	d_comp_used_date date,
	d_comp_used_time interval,
	c_comp_status varchar(255),
	f_rc_avail_dlrs numeric,
	f_rc_dlrs_issued numeric,
	f_rc_num_issued numeric,
	f_rc_dlrs_used numeric,
	f_rc_num_used numeric,
	f_num_foreign_rc numeric,
	f_dlrs_foreign_rc numeric,
	f_cw_dlrs_issued numeric,
	f_cw_dlrs_used numeric,
	c_comp_type varchar(255),
	i_comp_worth_profile numeric,
	f_cw_dlrs_avail numeric,
	c_comp_prof_used varchar(255),
	c_outlet_cat varchar(255),
	c_outlet_cd varchar(255),
	c_dept_cd varchar(255),
	c_compor_name varchar(255),
	c_compor_code varchar(255),
	i_reward_credit_num numeric,
	c_quality_cd boolean,
	d_timestamp timestamp,
	c_transaction_id numeric,
	c_non_decrementing_comps boolean,
	c_comp_comment varchar(255),
	i_dmid_2 numeric,
	i_xref_dmid numeric,
	c_quality_cd_2 boolean,
	d_timestamp_2 timestamp,
	account_c_prop_cd_fk varchar(18)
		constraint comp_detail_fk_account
			references account (sfid)
);
