create table caesars.eventTypes (
	id serial primary key,
	routing varchar,
	eventType varchar,
	eventGroupType varchar
);

insert into caesars.eventTypes (routing,eventType,eventGroupType) values
('HET.TEST.HAR.CLV.LMS.RESERVATION-CANCEL.PUB','RESERVATION-CANCEL','hotel'),
('HET.TEST.HAR.CLV.LMS.RESERVATION-CHECKOUT.PUB','RESERVATION-CHECKOUT','hotel'),
('HET.TEST.HAR.CLV.LMS.RESERVATION-CREATE.PUB','RESERVATION-CREATE','hotel'),
('HET.TEST.HAR.PDB.GUEST-SCORE.PUB','GUEST-SCORE','guest'),
('HET.TEST.HAR.PDB.GUEST-TIER.PUB','GUEST-TIER','guest'),
('HET.TEST.HAR.CLV.LMS.RESERVATION-CHECKIN.PUB','RESERVATION-CHECKIN','hotel'),
('HET.TEST.HAR.PDB.GUEST-ADD.PUB','GUEST-ADD','guest'),
('HET.TEST.HAR.CHE.CASINO.GAME-CARDOUT','GAME-CARDOUT','game'),
('HET.TEST.HAR.CHE.CASINO.GAME-CARDIN','GAME-CARDIN','game');