CREATE TABLE caesars.gst_slot_rating_dtl (
  id BIGSERIAL,
  i_cms_dmid VARCHAR(12),
  c_prop_cd VARCHAR(3),
  d_rating_date DATE,
  c_game_cd VARCHAR(12),
  f_denom NUMERIC(10,2),
  f_coin_in NUMERIC(10,2),
  f_coin_out NUMERIC(10,2),
  d_start_time TIME WITHOUT TIME ZONE,
  d_end_time TIME WITHOUT TIME ZONE,
  f_theo_win NUMERIC(10,2),
  f_play_time NUMERIC(10,2),
  f_winloss NUMERIC(10,2),
  c_prep_by VARCHAR(10),
  c_ent_by VARCHAR(10),
  d_trans_date DATE,
  i_rs_seq_num INTEGER,
  i_mach_num INTEGER,
  i_handle_pulls INTEGER,
  f_jackpot_amt NUMERIC(10,2),
  c_quality_cd VARCHAR(12),
  d_timestamp TIMESTAMP WITHOUT TIME ZONE,
  contact VARCHAR(18),
  CONSTRAINT gst_slot_rating_dtl_pkey PRIMARY KEY(id)
) 
WITH (oids = false);