CREATE TABLE caesars.gst_hotel_activity_vedw (
  id BIGSERIAL,
  f_reserve_id VARCHAR(12),
  c_orig_prop_cd VARCHAR(3),
  c_prop_cd VARCHAR(3),
  c_activity_status VARCHAR(1),
  i_stay_id VARCHAR(12),
  c_pri_cas_guest_id VARCHAR(12),
  i_dmid VARCHAR(12),
  i_cms_dmid VARCHAR(12),
  c_first_name TEXT,
  c_last_name TEXT,
  c_sec_cas_guest_id VARCHAR(12),
  i_sec_dmid VARCHAR(12),
  i_sec_cms_dmid VARCHAR(12),
  d_transaction_dt DATE,
  d_reserve_dt DATE,
  d_reserve_rpt_period DATE,
  d_cancel_dt DATE,
  d_cancel_rpt_period DATE,
  d_arrival_dt DATE,
  d_departure_dt DATE,
  c_confirm_id VARCHAR(12),
  c_cancel_id VARCHAR(12),
  c_share_id VARCHAR(12),
  i_nbr_shares INTEGER,
  c_reservation_agent_id VARCHAR(24),
  c_cancel_agent_id VARCHAR(24),
  c_checkin_agent_id VARCHAR(24),
  c_checkout_agent_id VARCHAR(24),
  c_transaction_agent_id VARCHAR(24),
  c_wing_cd VARCHAR(3),
  c_original_wing_cd VARCHAR(3),
  c_rm_type VARCHAR(5),
  c_original_rm_type VARCHAR(5),
  c_rm_nbr VARCHAR(12),
  i_rm_night INTEGER,
  i_nbr_rooms INTEGER,
  i_nbr_occupants INTEGER,
  i_group_id INTEGER,
  c_occupant_type TEXT,
  c_source_cd VARCHAR(3),
  c_rate_plan VARCHAR(12),
  c_group_cd VARCHAR(12),
  c_group_type TEXT,
  c_address_1 TEXT,
  c_address_2 TEXT,
  c_city TEXT,
  c_state_cd VARCHAR(12),
  c_zip_cd VARCHAR(12),
  d_dob DATE,
  c_confirm_email TEXT,
  c_email_contact_flag VARCHAR(12),
  c_offer_id VARCHAR(24),
  i_customer_segment INTEGER,
  i_customer_segment_adj INTEGER,
  c_tracking VARCHAR(12),
  c_settle_method VARCHAR(3),
  c_credit_card_nbr VARCHAR(24),
  c_credit_card_exp_dt VARCHAR(12),
  c_credit_card_auth_nbr VARCHAR(4),
  f_deposit_amt_req NUMERIC(10,2),
  f_deposit_credit_card_chg NUMERIC(10,2),
  f_room_rev_reserved NUMERIC(10,2),
  f_room_tax_reserved NUMERIC(10,2),
  d_checkin_dt DATE,
  d_checkin_time TIME WITHOUT TIME ZONE,
  d_checkin_rpt_period DATE,
  c_checkin_location TEXT,
  d_checkout_dt DATE,
  d_checkout_time TIME WITHOUT TIME ZONE,
  d_checkout_rpt_period DATE,
  c_checkout_location VARCHAR(24),
  f_room_rev NUMERIC(10,2),
  f_fb_rev NUMERIC(10,2),
  f_other_rev NUMERIC(10,2),
  f_comp_room_rev NUMERIC(10,2),
  f_comp_fb_rev NUMERIC(10,2),
  f_comp_other_rev NUMERIC(10,2),
  i_checkin_yr INTEGER,
  i_checkin_mn INTEGER,
  i_checkin_dy INTEGER,
  i_checkin_hr INTEGER,
  i_checkin_min INTEGER,
  i_checkin_sec INTEGER,
  i_checkout_yr INTEGER,
  i_checkout_mn INTEGER,
  i_checkout_dy INTEGER,
  i_checkout_hr INTEGER,
  i_checkout_min INTEGER,
  i_checkout_sec INTEGER,
  c_quality_cd VARCHAR(12),
  d_timestamp TIMESTAMP WITHOUT TIME ZONE,
  c_prop_cd_fk VARCHAR(18),
  source_code_fk VARCHAR(18),
  hotel_act_status_code_fk VARCHAR(18),
  customer_control_segments_fk VARCHAR(18),
  contact_fk VARCHAR(18),
  customer_control_segments_adj_fk VARCHAR(18),
  CONSTRAINT gst_hotel_activity_vedw_pkey PRIMARY KEY(id)
) 
WITH (oids = false);

CREATE UNIQUE INDEX gst_hotel_activity_vedw_idx ON caesars.gst_hotel_activity_vedw
  USING btree (i_stay_id COLLATE pg_catalog."default");