CREATE TABLE caesars.gst_table_rating_dtl (
  id BIGSERIAL,
  c_prop_cd VARCHAR(3),
  i_cms_dmid VARCHAR(12),
  i_rating_num INTEGER,
  d_rating_date DATE,
  i_rating_hyd INTEGER,
  d_trans_date DATE,
  d_trans_time TIME WITHOUT TIME ZONE,
  i_trans_hyd INTEGER,
  c_company TEXT,
  c_shift VARCHAR(12),
  c_pit_num VARCHAR(12),
  c_prop_game_cd VARCHAR(12),
  c_table_num VARCHAR(12),
  c_rate_type VARCHAR(12),
  i_countercheck_cnt INTEGER,
  f_countercheck NUMERIC(10,2),
  f_cash NUMERIC(10,2),
  f_avg_bet_1 NUMERIC(10,2),
  f_avg_bet_2 NUMERIC(10,2),
  f_avg_bet_3 NUMERIC(10,2),
  f_avg_bet_4 NUMERIC(10,2),
  f_avg_bet_5 NUMERIC(10,2),
  f_avg_bet_6 NUMERIC(10,2),
  f_hands_played NUMERIC(10,2),
  f_handle NUMERIC(10,2),
  f_buy_in NUMERIC(10,2),
  f_cash_out NUMERIC(10,2),
  d_seq_rating_start_time TIME WITHOUT TIME ZONE,
  d_rating_start_time TIME WITHOUT TIME ZONE,
  d_rating_end_time TIME WITHOUT TIME ZONE,
  i_minutes_played INTEGER,
  f_theo_win NUMERIC(10,2),
  f_comp_worth NUMERIC(10,2),
  c_rated_by VARCHAR(12),
  c_entered_by VARCHAR(12),
  c_game_speed VARCHAR(12),
  c_quality_cd VARCHAR(12),
  d_timestamp TIMESTAMP WITHOUT TIME ZONE,
  contact VARCHAR(18),
  CONSTRAINT gst_table_rating_dtl_pkey PRIMARY KEY(id)
) 
WITH (oids = false);