CREATE TABLE caesars.lms_room_type_desc_sda (
  id BIGSERIAL,
  c_prop_cd VARCHAR(3),
  c_rm_type VARCHAR(3),
  c_room_quality VARCHAR(24),
  i_room_quality_sort INTEGER,
  c_room_smoking VARCHAR(24),
  c_room_bed_type VARCHAR(24),
  i_room_bet_type_sort INTEGER,
  c_room_accessible VARCHAR(24),
  c_room_desc1 VARCHAR(1),
  i_rm_sort_1 INTEGER,
  c_room_desc2 VARCHAR(1),
  i_rm_sort_2 INTEGER,
  c_room_desc3 VARCHAR(1),
  i_rm_sort_3 INTEGER,
  c_room_desc4 VARCHAR(1),
  i_rm_sort_4 INTEGER,
  c_user_flag1 VARCHAR(1),
  c_user_flag2 VARCHAR(1),
  c_user_flag3 VARCHAR(1),
  c_user_flag4 VARCHAR(1),
  c_user_flag5 VARCHAR(1),
  c_user_flag6 VARCHAR(1),
  c_user_flag7 VARCHAR(1),
  c_user_flag8 VARCHAR(1),
  i_user_score1 INTEGER,
  i_user_score2 INTEGER,
  i_user_score3 INTEGER,
  i_user_score4 INTEGER,
  f_user_amt1 NUMERIC(10,2),
  f_user_amt2 NUMERIC(10,2),
  f_user_amt3 NUMERIC(10,2),
  f_user_amt4 NUMERIC(10,2),
  d_last_update_date DATE,
  c_prop_cd_fk VARCHAR(18),
  CONSTRAINT lms_room_type_desc_sda_pkey PRIMARY KEY(id)
) 
WITH (oids = false);

CREATE UNIQUE INDEX lms_room_type_desc_sda__prop__rm_type_uidx ON caesars.lms_room_type_desc_sda
  USING btree (c_prop_cd COLLATE pg_catalog."default", c_rm_type COLLATE pg_catalog."default");