CREATE TABLE caesars.lms_source_desc_sda (
  id BIGSERIAL,
  c_prop_cd VARCHAR(3),
  c_prop_cd_fk VARCHAR(18),
  c_source_group VARCHAR(2),
  c_source_cd VARCHAR(2),
  source_code_fk BIGINT,
  c_source_cd_desc VARCHAR(50),
  c_rms_group_source_cd VARCHAR(50),
  c_source_cat_sda VARCHAR(50),
  i_source_cat_sda_sort INTEGER,
  c_source_cat1 VARCHAR(50),
  i_source_cat1_sort INTEGER,
  c_source_cat2 VARCHAR(50),
  i_source_cat2_sort INTEGER,
  c_source_cat3 VARCHAR(50),
  i_source_cat3_sort INTEGER,
  c_source_cat4 VARCHAR(50),
  i_source_cat4_sort INTEGER,
  c_source_cat5 VARCHAR(50),
  i_source_cat5_sort INTEGER,
  c_source_cat6 VARCHAR(50),
  i_source_cat6_sort INTEGER,
  c_user_flag1 VARCHAR(50),
  c_user_flag2 VARCHAR(50),
  c_user_flag3 VARCHAR(50),
  c_user_flag4 VARCHAR(50),
  c_user_flag5 VARCHAR(50),
  c_user_flag6 VARCHAR(50),
  c_user_flag7 VARCHAR(50),
  c_user_flag8 VARCHAR(50),
  i_user_score1 INTEGER,
  i_user_score2 INTEGER,
  i_user_score3 INTEGER,
  i_user_score4 INTEGER,
  f_user_amt1 NUMERIC,
  f_user_amt2 NUMERIC,
  f_user_amt3 NUMERIC,
  f_user_amt4 NUMERIC,
  d_last_update_ts TIMESTAMP WITHOUT TIME ZONE,
  c_quality_cd VARCHAR(1),
  d_timestamp TIMESTAMP WITHOUT TIME ZONE,
  CONSTRAINT lms_source_desc_sda_idx UNIQUE(c_prop_cd, c_source_cd),
  CONSTRAINT lms_source_desc_sda_pkey PRIMARY KEY(id),
  CONSTRAINT lms_source_desc_sda_fk FOREIGN KEY (source_code_fk)
    REFERENCES caesars.source_code(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
    NOT DEFERRABLE
) 
WITH (oids = false);