CREATE TABLE caesars.lms_hotel_activity (
  id BIGSERIAL,
  f_reserve_id VARCHAR(12),
  c_prop_cd VARCHAR(3),
  c_activity_status VARCHAR(1),
  i_xref_dmid VARCHAR(12),
  c_pri_cas_guest_id VARCHAR(12),
  c_first_name TEXT,
  c_last_name TEXT,
  c_sec_cas_guest_id VARCHAR(12),
  i_sec_xref_dmid VARCHAR(12),
  d_transaction_dt DATE,
  d_reserve_dt DATE,
  d_cancel_dt DATE,
  d_arrival_dt DATE,
  d_departure_dt DATE,
  c_confirm_id VARCHAR(5),
  c_cancel_id VARCHAR(5),
  c_share_id VARCHAR(12),
  i_nbr_shares INTEGER,
  c_reservation_agent_id VARCHAR(12),
  c_cancel_agent_id VARCHAR(12),
  c_checkin_agent_id VARCHAR(12),
  c_checkout_agent_id VARCHAR(12),
  c_transaction_agent_id VARCHAR(12),
  c_wing_cd VARCHAR(2),
  c_original_rm_type VARCHAR(6),
  c_rm_nbr VARCHAR(12),
  i_rm_night INTEGER,
  i_nbr_rooms INTEGER,
  i_nbr_occupants INTEGER,
  c_occupant_type TEXT,
  c_source_cd VARCHAR(12),
  c_rate_plan VARCHAR(12),
  c_group_cd VARCHAR(12),
  c_group_type TEXT,
  c_address_1 TEXT,
  c_address_2 TEXT,
  c_city TEXT,
  c_state_cd VARCHAR(12),
  c_zip_cd VARCHAR(12),
  d_dob DATE,
  c_confirm_email TEXT,
  c_email_contact_flag VARCHAR(12),
  c_offer_id VARCHAR(24),
  i_customer_segment INTEGER,
  c_tracking VARCHAR(12),
  c_settle_method VARCHAR(3),
  c_credit_card_nbr VARCHAR(24),
  c_credit_card_exp_dt VARCHAR(12),
  c_credit_card_auth_nbr VARCHAR(4),
  f_deposit_amt_req NUMERIC(10,2),
  f_deposit_credit_card_chg NUMERIC(10,2),
  f_room_rev_reserved NUMERIC(10,2),
  f_room_tax_reserved NUMERIC(10,2),
  d_checkin_dt DATE,
  d_checkin_time TIME WITHOUT TIME ZONE,
  c_checkin_location TEXT,
  d_checkout_dt DATE,
  d_checkout_time TIME WITHOUT TIME ZONE,
  c_checkout_location VARCHAR(12),
  f_room_rev NUMERIC(10,2),
  f_fb_rev NUMERIC(10,2),
  f_other_rev NUMERIC(10,2),
  f_comp_room_rev NUMERIC(10,2),
  f_comp_fb_rev NUMERIC(10,2),
  f_comp_other_rev NUMERIC(10,2),
  c_quality_cd VARCHAR(12),
  d_timestamp TIMESTAMP WITHOUT TIME ZONE,
  c_rm_type VARCHAR(12),
  c_original_wing_cd VARCHAR(2),
  c_prop_cd_fk VARCHAR(18),
  lms_room_type_desc_sda_fk VARCHAR(18),
  hotel_wing_codes__fk VARCHAR(18),
  source_code_fk VARCHAR(18),
  hotel_act_status_code_fk VARCHAR(18),
  customer_control_segments_fk VARCHAR(18),
  contact_pri_fk VARCHAR(18),
  contact_sec_fk VARCHAR(18),
  CONSTRAINT lms_hotel_activity__prop__reserve_id_key UNIQUE(c_prop_cd, f_reserve_id),
  CONSTRAINT lms_hotel_activity_pkey PRIMARY KEY(id)
) 
WITH (oids = false);