-- DROP TABLE caesars.pdb_trip;

CREATE TABLE caesars.pdb_trip
(
  id bigserial NOT NULL,
  i_pdb_trip_id character varying(11),
  i_dmid character varying(11),
  c_prop_cd character varying(3),
  d_start_dt date,
  d_end_dt date,
  d_rpt_per date,
  i_nbr_days integer,
  c_casino_flag character varying(1),
  c_hotel_flag character varying(1),
  c_curr_flag character varying(1),
  c_w2g_flag character varying(1),
  c_as_brand_flag character varying(1),
  c_as_cms_flag character varying(1),
  c_first_prop_visit character varying(1),
  c_home_prop_cd character varying(3),
  c_week_cd character varying(1),
  c_rated_trip character varying(1),
  i_nbr_offers_red integer,
  i_nbr_offers_unred integer,
  i_events integer,
  i_trip_nbr integer,
  i_brand_trip_nbr integer,
  c_pos_flag character varying(1),
  c_cons_rev_flag character varying(1),
  i_rated_days integer,
  i_nbr_trip_game integer,
  i_nbr_trip_slot integer,
  i_nbr_trip_oth integer,
  i_rated_trips integer,
  i_nbr_cms_trips integer,
  i_comped_trip integer,
  f_theo_all numeric,
  f_theo_game numeric,
  f_theo_slot numeric,
  f_theo_oth numeric,
  f_actual_all numeric,
  f_actual_game numeric,
  f_actual_slot numeric,
  f_actual_oth numeric,
  f_comp_worth numeric,
  f_avgbet_game numeric,
  f_avgbet_slot numeric,
  f_avgbet_oth numeric,
  i_avgbet_div_game integer,
  i_avgbet_div_slot integer,
  i_avgbet_div_oth integer,
  f_cash_play_game numeric,
  f_cash_play_slot numeric,
  f_cash_play_oth numeric,
  f_marker_play_game numeric,
  f_marker_play_slot numeric,
  f_marker_play_oth numeric,
  i_len_of_play_game integer,
  i_len_of_play_slot integer,
  i_len_of_play_oth integer,
  f_room_comp_amt numeric,
  f_food_comp_amt numeric,
  f_other_comp_amt numeric,
  f_total_comp_amount numeric,
  i_stay integer,
  i_rm_night integer,
  f_room_rev numeric,
  f_fb_rev numeric,
  f_comp_rev numeric,
  f_other_rev numeric,
  i_nbr_rooms integer,
  i_nbr_occupants integer,
  i_nbr_pos_days integer,
  i_covers integer,
  i_nbr_trans integer,
  i_nbr_rev_centers integer,
  f_trans_amt numeric,
  f_pos_comp_amt numeric,
  i_nbr_line_item integer,
  i_line_item_qty integer,
  f_tax_amt numeric,
  f_room_chrg_amt numeric,
  f_discount_amt numeric,
  f_service_charge_amt numeric,
  f_food_amt numeric,
  f_liq_amt numeric,
  f_cash_chrg_amt numeric,
  f_beer_amt numeric,
  f_wine_amt numeric,
  f_retail_amt numeric,
  f_na_bev_amt numeric,
  f_misc_amt numeric,
  f_oth_amt numeric,
  f_pos_actual_profit_amt numeric,
  f_pos_avg_profit_amt numeric,
  i_nbr_cons_rev_days integer,
  f_food_fd_cash_rev numeric,
  f_food_cd_cash_rev numeric,
  f_food_qs_cash_rev numeric,
  f_food_bev_nc_cash_rev numeric,
  f_room_cash_rev numeric,
  f_package_cash_rev numeric,
  f_transport_cash_rev numeric,
  f_spa_cash_rev numeric,
  f_event_cash_rev numeric,
  f_entertain_cash_rev numeric,
  f_golf_cash_rev numeric,
  f_retail_owned_cash_rev numeric,
  f_retail_le_cash_rev numeric,
  f_other_cash_rev numeric,
  f_food_fd_comp_rev numeric,
  f_food_cd_comp_rev numeric,
  f_food_qs_comp_rev numeric,
  f_food_bev_nc_comp_rev numeric,
  f_room_comp_rev numeric,
  f_package_comp_rev numeric,
  f_transport_comp_rev numeric,
  f_spa_comp_rev numeric,
  f_event_comp_rev numeric,
  f_golf_comp_rev numeric,
  f_entertain_comp_rev numeric,
  f_retail_owned_comp_rev numeric,
  f_retail_le_comp_rev numeric,
  f_other_comp_rev numeric,
  f_food_fd_cash_tt numeric,
  f_food_cd_cash_tt numeric,
  f_food_qs_cash_tt numeric,
  f_food_bev_nc_cash_tt numeric,
  f_room_cash_tt numeric,
  f_package_cash_tt numeric,
  f_transport_cash_tt numeric,
  f_spa_cash_tt numeric,
  f_event_cash_tt numeric,
  f_entertain_cash_tt numeric,
  f_golf_cash_tt numeric,
  f_retail_owned_cash_tt numeric,
  f_retail_le_cash_tt numeric,
  f_other_cash_tt numeric,
  f_food_fd_comp_tt numeric,
  f_food_cd_comp_tt numeric,
  f_food_qs_comp_tt numeric,
  f_food_bev_nc_comp_tt numeric,
  f_room_comp_tt numeric,
  f_package_comp_tt numeric,
  f_transport_comp_tt numeric,
  f_spa_comp_tt numeric,
  f_event_comp_tt numeric,
  f_golf_comp_tt numeric,
  f_entertain_comp_tt numeric,
  f_retail_owned_comp_tt numeric,
  f_retail_le_comp_tt numeric,
  f_other_comp_tt numeric,
  f_food_fd_actual_profit numeric,
  f_food_cd_actual_profit numeric,
  f_food_qs_actual_profit numeric,
  f_food_bev_nc_actual_profit numeric,
  f_room_actual_profit numeric,
  f_package_actual_profit numeric,
  f_transport_actual_profit numeric,
  f_spa_actual_profit numeric,
  f_event_actual_profit numeric,
  f_entertain_actual_profit numeric,
  f_golf_actual_profit numeric,
  f_retail_owned_actual_profit numeric,
  f_retail_le_actual_profit numeric,
  f_other_actual_profit numeric,
  f_food_fd_avg_profit numeric,
  f_food_cd_avg_profit numeric,
  f_food_qs_avg_profit numeric,
  f_food_bev_nc_avg_profit numeric,
  f_room_avg_profit numeric,
  f_package_avg_profit numeric,
  f_transport_avg_profit numeric,
  f_spa_avg_profit numeric,
  f_event_avg_profit numeric,
  f_golf_avg_profit numeric,
  f_entertain_avg_profit numeric,
  f_retail_owned_avg_profit numeric,
  f_retail_le_avg_profit numeric,
  f_other_avg_profit numeric,
  c_quality_cd character varying(12),
  d_timestamp timestamp without time zone,
  f_tax_discount_oth_amt numeric,
  f_other_payment_amt numeric,
  f_total_payment_amt numeric,
  f_total_item_amt numeric,
  week_code_fk bigint,
  contact_fk character varying(18),
  account_c_prop_cd_fk character varying(18),
  account_c_home_prop_cd_fk character varying(18),
  CONSTRAINT pdb_trip_pkey PRIMARY KEY (id)
)
WITH (
OIDS=FALSE
);

-- ALTER TABLE caesars.pdb_trip DROP CONSTRAINT pdb_trip_fk_week_code;
ALTER TABLE caesars.pdb_trip
  ADD CONSTRAINT pdb_trip_fk_week_code FOREIGN KEY (week_code_fk)
REFERENCES caesars.week_code (id) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION;

-- UPDATE caesars.pdb_trip SET contact_fk = (SELECT c.sfid FROM salesforce.contact c WHERE c.winet_id__c = caesars.pdb_trip.i_dmid LIMIT 1);

-- UPDATE caesars.pdb_trip SET week_code_fk = (SELECT wc.id FROM caesars.week_code wc WHERE wc.c_week_cd = caesars.pdb_trip.c_week_cd);

-- UPDATE caesars.pdb_trip SET account_c_prop_cd_fk = (SELECT c.sfid FROM salesforce.account c
-- WHERE ((c.property_code__c = caesars.pdb_trip.c_prop_cd AND caesars.pdb_trip.c_prop_cd != 'CAC') OR ( caesars.pdb_trip.c_prop_cd = 'CAC' AND c.sfid = '0010v000004IsA7AAK' ) ));

-- UPDATE caesars.pdb_trip SET account_c_home_prop_cd_fk = (SELECT c.sfid FROM salesforce.account c
-- WHERE ((c.property_code__c = caesars.pdb_trip.c_home_prop_cd AND caesars.pdb_trip.c_home_prop_cd != 'CAC') OR ( caesars.pdb_trip.c_home_prop_cd = 'CAC' AND c.sfid = '0010v000004IsA7AAK' ) ));