CREATE TABLE caesars.pos_trans_hdr (
  id BIGSERIAL,
  c_pos_trans_id VARCHAR(50),
  c_prop_cd VARCHAR(3),
  c_pos_rev_center_cd VARCHAR(12),
  d_pos_trans_dt DATE,
  i_check_nbr INTEGER,
  d_pos_trans_start_time TIMESTAMP WITHOUT TIME ZONE,
  d_pos_trans_end_time TIMESTAMP WITHOUT TIME ZONE,
  c_trans_type_cd VARCHAR(1),
  i_open_from_check_nbr INTEGER,
  i_order_nbr INTEGER,
  i_xref_dmid VARCHAR(12),
  i_covers INTEGER,
  i_table_nbr VARCHAR(12),
  i_pos_employee_nbr INTEGER,
  c_pos_employee_name TEXT,
  f_sub_total_amt NUMERIC(10,2),
  f_tax_amt NUMERIC(10,2),
  f_trans_amt NUMERIC(10,2),
  i_nbr_line_item INTEGER,
  i_line_item_qty INTEGER,
  f_pos_comp_amt NUMERIC(10,2),
  f_room_chrg_amt NUMERIC(10,2),
  f_cash_chrg_amt NUMERIC(10,2),
  f_discount_amt NUMERIC(10,2),
  f_service_charge_amt NUMERIC(10,2),
  f_food_amt NUMERIC(10,2),
  f_liq_amt NUMERIC(10,2),
  f_beer_amt NUMERIC(10,2),
  f_wine_amt NUMERIC(10,2),
  f_retail_amt NUMERIC(10,2),
  f_misc_amt NUMERIC(10,2),
  f_na_bev_amt NUMERIC(10,2),
  f_oth_amt NUMERIC(10,2),
  c_quality_cd VARCHAR(12),
  d_timestamp TIMESTAMP WITHOUT TIME ZONE,
  f_tax_discount_oth_amt NUMERIC(10,2),
  f_other_payment_amt NUMERIC(10,2),
  f_total_payment_amt NUMERIC(10,2),
  f_total_item_amt NUMERIC(10,2),
  c_file_prop_cd VARCHAR(3),
  CONSTRAINT pos_trans_hdr_pkey PRIMARY KEY(id)
) 
WITH (oids = false);